# fly.toml app configuration file generated for sena-lichtlabs-org on 2025-03-22T01:33:03+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sena-lichtlabs-org'
primary_region = 'sin'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
